version: 1.0.{build}
image: Visual Studio 2019
install:
  - dotnet tool install -g Cake.Tool --version 0.37.0
  - SET JAVA_HOME=C:\Program Files\Java\jdk11
  - SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
- cmd: >-
    dotnet cake -Target=CreateArtifact -buildConfig=Release

    dotnet cake -Host="Rider" -Target=CreateArtifact -buildConfig=Release

    dotnet cake -Target=Sonar -buildConfig=Release
test: off
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - 'tools -> build.cake'
