version: 1.0.{build}
image: Visual Studio 2017
install:
  - dotnet tool install -g Cake.Tool --version 0.33.0 
build_script:
- cmd: >-
    dotnet cake -Target=CreateArtifact -buildConfig=Release

    dotnet cake -Host="Rider" -Target=CreateArtifact -buildConfig=Release
test: off
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - 'tools -> build.cake'
